export const APP_NAME = "Namoe Go";

export const copy = {
  nav: { home: "Beranda", tenants: "Tenant", map: "Peta", schedule: "Jadwal", passport: "Paspor" },
  home: {
    dates: "22 sampai 25 Oktober 2026",
    venue: "Main Atrium, PIK Avenue Mall",
    askSpeaker: "Tanya pembicara",
    allTenants: "Lihat semua tenant",
    openMap: "Buka peta",
    startPassport: "Mulai paspor",
    scheduleTitle: "Jadwal",
    tenantsCount: (n: number) => `${n} tenant`,
  },
  directory: {
    search: "Cari tenant",
    all: "Semua",
    booth: (c: string) => `Booth ${c}`,
    empty: "Tidak ada tenant yang cocok. Coba kata lain atau pilih kategori lain.",
    seeOnMap: "Lihat di peta",
  },
  tenant: {
    promo: "Promo di booth",
    atBooth: "Di booth ini",
    allDay: "Sepanjang hari",
    ask: "Tanya tenant",
    askSoon: "Fitur tanya tenant menyusul",
    seeOnMap: "Lihat di peta",
    booth: (label: string) => `Booth ${label}`,
    instagram: "Instagram",
    tiktok: "TikTok",
    shop: "Toko online",
    notFound: "Tenant tidak ditemukan",
    pinned: "Disematkan",
  },
  map: {
    title: "Peta booth",
    hint: "Ketuk booth untuk melihat tenant",
    empty: "Belum terisi",
    enlarge: "Perbesar",
    shrink: "Perkecil",
    stage: "Panggung",
    seating: "Area duduk",
    gate: "Gerbang",
    openTenant: "Buka halaman tenant",
    legend: "Kategori",
  },
  qa: {
    tabQuestions: "Tanya pembicara",
    tabThanks: "Ucapan",
    placeholder: "Tulis pertanyaan kamu",
    thanksPlaceholder: "Tulis ucapan untuk pembicara",
    name: "Nama, boleh dikosongkan",
    send: "Kirim",
    anon: "Anonim",
    answered: "Sudah dijawab",
    answeredCount: (n: number) => `${n} pertanyaan sudah dijawab`,
    emptyQuestions: "Belum ada pertanyaan. Jadi yang pertama bertanya.",
    emptyThanks: "Belum ada ucapan. Tulis ucapan pertama untuk pembicara.",
  },
  passport: {
    title: "Paspor booth",
    subtitle: (t: number) => `Kumpulkan ${t} stempel dari booth yang kamu kunjungi`,
    progress: (n: number, t: number) => `${n} dari ${t} stempel`,
    stamped: (c: string) => `Stempel baru dari booth ${c}`,
    already: (c: string) => `Booth ${c} sudah pernah distempel`,
    unknown: "Kode booth tidak dikenal",
    complete: "Paspor kamu lengkap",
    showCode: "Tunjukkan kode ini di meja informasi",
    redeemed: "Hadiah sudah diambil",
    prizePlaceholder: "Hadiah diisi oleh panitia",
    visited: "Booth yang sudah dikunjungi",
    howTo: "Scan kode QR di setiap booth untuk mendapat stempel",
  },
  organizer: {
    title: "Panel panitia",
    redeem: "Tukar hadiah",
    boothLinks: "Tautan booth",
    sessions: "Sesi",
    codeLabel: "Kode paspor",
    find: "Cari",
    markRedeemed: "Tandai sudah ditukar",
    markAnswered: "Tandai sudah dijawab",
    unmarkAnswered: "Batalkan",
    hide: "Sembunyikan",
    show: "Tampilkan",
    notFound: "Kode tidak ditemukan",
    stats: {
      tenants: "Tenant",
      questions: "Pertanyaan",
      passportsStarted: "Paspor dimulai",
      passportsDone: "Paspor lengkap",
    },
  },
  errors: {
    bodyTooShort: "Tulis minimal 3 karakter",
    bodyTooLong: "Maksimal 280 karakter",
    generic: "Terjadi kesalahan, coba lagi",
  },
} as const;
