export const APP_NAME = "Namoe Go";

export const copy = {
  nav: { home: "Beranda", tenants: "Tenant", map: "Peta", schedule: "Jadwal", passport: "Paspor", feed: "Feed" },
  common: {
    back: "Kembali",
    close: "Tutup",
    open: "Buka",
    search: "Cari",
    save: "Simpan",
    cancel: "Batal",
    remove: "Hapus",
    add: "Tambah",
  },
  home: {
    subtitle: "Panduan pengunjung Namoe Market",
    dates: "22 sampai 25 Oktober 2026",
    venue: "Main Atrium, PIK Avenue Mall",
    openingTalk: "Talkshow pembuka",
    nextTalks: "Talkshow berikutnya",
    allSchedule: "Semua jadwal",
    askSpeaker: "Tanya pembicara",
    mapHint: "Denah booth",
    tenantsCount: (n: number) => `${n} brand`,
    sessionsCount: (n: number) => `${n} talkshow`,
    passportProgress: (n: number, t: number) => `${n} dari ${t} stempel`,
    passportComplete: "Lengkap",
    noSessions: "Belum ada sesi di hari ini",
  },
  directory: {
    search: "Cari tenant atau booth",
    all: "Semua",
    count: (n: number) => `${n} brand, urut nama`,
    countIn: (n: number, cat: string) => `${n} brand di ${cat}`,
    emptyTitle: "Tidak ada tenant yang cocok",
    emptyBody: "Coba kata lain atau pilih kategori lain.",
    saved: "Tersimpan",
    savedCount: (n: number) => `${n} brand tersimpan`,
    savedEmptyTitle: "Belum ada tenant tersimpan",
    savedEmptyBody: "Ketuk ikon hati di kartu tenant untuk menyimpannya di sini.",
  },
  tenant: {
    promo: "Promo di booth",
    atBooth: "Di booth ini",
    allDay: "Sepanjang hari",
    everyDay: "Setiap hari",
    ask: "Tanya tenant",
    askEmptyTitle: "Belum ada pertanyaan",
    askEmptyBody: "Tanya soal produk, ukuran, atau stok. Tenant menjawab langsung di sini.",
    askWrite: "Tulis pertanyaan",
    askPlaceholder: "Tulis pertanyaan kamu untuk tenant",
    openMap: "Buka peta",
    booth: (label: string) => `Booth ${label}`,
    boothLine: (label: string) => `Booth ${label}`,
    photosTitle: "Foto produk",
    photoAlt: (name: string, n: number) => `Foto ${n} dari ${name}`,
    instagram: "Instagram",
    tiktok: "TikTok",
    shop: "Toko online",
    shopee: "Shopee",
    tokopedia: "Tokopedia",
    notFound: "Tenant tidak ditemukan",
    notFoundHint: "Tautan mungkin salah atau tenant sudah tidak terdaftar.",
    backToDirectory: "Kembali ke daftar tenant",
    pinned: "Disematkan",
    reply: "Jawaban tenant",
    anon: "Anonim",
    save: "Simpan tenant ini",
    unsave: "Hapus dari simpanan",
    location: {
      front: "Blok depan, dekat lobi timur",
      middle: "Blok tengah, dekat panggung",
      back: "Blok belakang, dekat area duduk",
      fnb: "Deretan makanan dan minuman, dekat gerbang",
    },
  },
  map: {
    title: "Peta",
    hint: "Ketuk booth untuk melihat tenant. Warna mengikuti kategori di atas.",
    empty: "Belum terisi",
    zoomIn: "Perbesar",
    zoomOut: "Perkecil",
    fit: "Pas layar",
    stage: "Panggung",
    seating: "Area duduk",
    gate: "Gerbang",
    openTenant: "Buka halaman tenant",
    close: "Tutup",
    unit: (n: number) => `${n} unit booth`,
    filterActive: (n: number, cat: string) => `Filter aktif: ${n} booth ${cat}. Booth lain diredupkan.`,
    ariaLabel: "Denah booth Namoe Market",
  },
  qa: {
    tabQuestions: "Tanya pembicara",
    tabThanks: "Ucapan",
    placeholder: "Tulis pertanyaan kamu",
    thanksPlaceholder: "Tulis ucapan untuk pembicara",
    name: "Nama, boleh dikosongkan",
    send: "Kirim",
    anon: "Anonim",
    answeredLabel: "Sudah dijawab",
    answered: (n: number) => `${n} pertanyaan sudah dijawab`,
    helper: "Pertanyaan dengan dukungan terbanyak naik ke atas. Kamu bisa dukung satu kali per pertanyaan.",
    emptyTitle: "Belum ada pertanyaan",
    emptyBody: "Jadi yang pertama bertanya ke pembicara.",
    emptyThanksTitle: "Belum ada ucapan",
    emptyThanksBody: "Tulis ucapan pertama untuk pembicara.",
    counter: (n: number, max: number) => `${n} dari ${max} karakter`,
    upvote: "Dukung pertanyaan ini",
    sessionNotFound: "Sesi tidak ditemukan",
    backToSchedule: "Kembali ke jadwal",
    speakers: "Pembicara",
    speakerOrganizer: "penyelenggara Namoe Market",
  },
  speaker: {
    notFound: "Pembicara tidak ditemukan",
    sessions: "Sesi bersama",
  },
  passport: {
    title: "Paspor",
    progress: (n: number, t: number) => `${n} dari ${t} stempel`,
    progressShort: (n: number, t: number) => `${n} dari ${t}`,
    collect: (t: number) => `Kumpulkan ${t} stempel`,
    collectBody: (t: number) => `Satu stempel per booth yang kamu kunjungi. Lengkap ${t}, tukar hadiah di meja informasi.`,
    left: (n: number) => `${n} stempel lagi`,
    leftBody: (t: number) => `Lengkap ${t}, tukar hadiah di meja informasi.`,
    done: (t: number) => `${t} dari ${t} stempel`,
    keepGoing: "Kamu boleh terus mengumpulkan stempel, hadiahnya satu per paspor.",
    how: "Cara dapat stempel",
    howBody: "Scan kode QR di meja booth mana pun. Stempel masuk otomatis ke paspor ini, tanpa daftar.",
    seeBooths: "Lihat daftar booth",
    newStamp: (tenant: string, code: string) => `Stempel baru dari ${tenant}, booth ${code}`,
    newStampEmpty: (code: string) => `Stempel baru dari booth ${code}`,
    already: (code: string) => `Booth ${code} sudah ada di paspor kamu`,
    unknown: "Kode QR tidak dikenal",
    complete: "Paspor kamu lengkap",
    completePill: "Lengkap",
    show: "Tunjukkan kode ini di meja informasi",
    redeemed: "Hadiah sudah diambil",
    prize: "Hadiah",
    visited: "Booth yang sudah dikunjungi",
    stampsLabel: "Stempel",
    slot: (n: number) => `Stempel ${n}, masih kosong`,
  },
  feed: {
    title: "Feed",
    write: "Tulis kabar",
    emptyTitle: "Belum ada kabar",
    emptyBody: "Foto plus satu kalimat dari pengunjung dan tenant.",
    placeholder: "Satu kalimat tentang apa yang kamu lihat",
    photoUrl: "Tautan foto",
    photoUpload: "Unggah dari galeri",
    sent: "Kabar terkirim",
    tenantBadge: "Tenant",
    hiddenTag: "Disembunyikan",
  },
  tenantEdit: {
    title: "Kelola booth",
    saved: "Tersimpan",
    dirty: "Belum disimpan",
    saveAll: "Simpan perubahan",
    saving: "Menyimpan",
    viewPublic: "Lihat halaman tenant",
    warning: "Simpan tautan halaman ini. Siapa pun yang memilikinya bisa mengubah booth kamu.",
    photos: "Foto produk",
    photosCount: (n: number, max: number) => `${n} dari ${max}`,
    photosHint: "Tempel tautan foto dari Instagram, atau unggah dari galeri. Foto pertama jadi foto utama di daftar tenant.",
    primary: "Utama",
    logo: "Logo",
    addPhoto: "Tambah",
    addLogo: "Tambah logo",
    removePhoto: "Hapus foto",
    pasteUrl: "Tempel tautan foto",
    useUrl: "Pakai tautan",
    upload: "Unggah dari galeri",
    uploadHint: "JPG, PNG, atau WebP, maksimal 5 MB.",
    intro: "Perkenalan brand",
    introPlaceholder: "Ceritakan brand kamu dalam beberapa kalimat",
    introCounter: (n: number, max: number) => `${n} dari ${max} karakter`,
    promo: "Promo di booth",
    promoPlaceholder: "Contoh: diskon 20% untuk pembelian kedua",
    promoShown: "Tampil",
    promoHidden: "Sembunyi",
    slots: "Di booth ini",
    slotAdd: "Tambah",
    slotTime: "Jam, contoh 14.00",
    slotTitle: "Nama kegiatan",
    slotRemove: "Hapus kegiatan",
    links: "Tautan",
    instagram: "Instagram, nama akun atau tautan",
    tiktok: "TikTok, nama akun atau tautan",
    marketplace: "Tautan Shopee atau Tokopedia",
    posts: "Tanya tenant",
    unanswered: (n: number) => `${n} belum dibalas`,
    yourReply: "Jawaban kamu",
    reply: "Balas",
    replyPlaceholder: "Tulis jawaban kamu",
    sendReply: "Kirim jawaban",
    pin: "Sematkan",
    unpin: "Lepas sematan",
    hide: "Sembunyikan",
    unhide: "Tampilkan",
    postsEmptyTitle: "Belum ada pertanyaan",
    postsEmptyBody: "Pertanyaan pengunjung dari halaman tenant kamu muncul di sini.",
    feed: "Kabar untuk Feed",
    feedEmptyTitle: "Belum ada kabar dari booth kamu",
    feedEmptyBody: "Foto plus satu kalimat. Tampil di Feed dengan lencana tenant.",
    feedWrite: "Tulis kabar",
    feedPlaceholder: "Satu kalimat, maksimal 140 karakter",
    feedSent: "Kabar tayang di Feed",
    notFoundTitle: "Tautan tidak dikenal",
    notFoundBody: "Periksa kembali tautan yang dikirim panitia, atau minta tautan baru.",
  },
  organizer: {
    title: "Panel panitia",
    summary: "Ringkasan",
    summaryHint: "Angka sejak aplikasi dibuka. Diperbarui setiap kali halaman dimuat.",
    printQr: "Cetak QR booth",
    questions: "Tanya pembicara",
    questionsHint: "Pilih sesi untuk moderasi. Tandai sudah dijawab, sembunyikan yang tidak pantas.",
    tenants: "Tenant",
    tenantsHint: "Tautan edit untuk tiap tenant, jumlah kunjungan, dan moderasi Tanya tenant serta Feed.",
    redeem: "Tukar hadiah",
    redeemHint: "Masukkan kode 6 karakter dari paspor pengunjung.",
    boothLinks: "Tautan booth",
    boothLinksHint: "Satu tautan per booth. Ketuk di ponsel untuk mensimulasikan scan QR, atau cetak lembar QR.",
    sessions: "Sesi",
    sessionsHint: "Buka untuk moderasi dan tandai sudah dijawab",
    codeLabel: "Kode paspor",
    check: "Cek",
    markRedeemed: "Tandai sudah ditukar",
    markAnswered: "Tandai sudah dijawab",
    unmarkAnswered: "Batalkan",
    hide: "Sembunyikan",
    show: "Tampilkan",
    notFound: "Kode tidak ditemukan",
    codeValid: (n: number) => `Kode valid, ${n} stempel, belum ditukar`,
    stampCount: (n: number) => `${n} stempel`,
    completedAt: "Lengkap pada",
    redeemedAt: "Ditukar pada",
    notRedeemed: "Belum ditukar",
    alreadyRedeemed: "Sudah ditukar",
    questionsCount: (n: number) => `${n} pertanyaan`,
    upvotesCount: (n: number) => `${n} dukungan`,
    hiddenTag: "Disembunyikan",
    openQuestions: "Pertanyaan terbuka",
    answeredQuestions: "Sudah dijawab",
    boothCode: "Booth",
    tenantCol: "Tenant",
    linkCol: "Tautan",
    emptyBooth: "Kosong",
    allTenants: (n: number) => `Semua ${n}`,
    editLink: "Tautan edit",
    qr: "QR",
    views: (n: number) => `${n} kunjungan`,
    posts: (n: number) => `${n} pertanyaan tenant`,
    feedPosts: (n: number) => `${n} kabar`,
    postsPerDay: "Kabar per hari",
    outsideEvent: "Di luar hari acara",
    visitorFeed: "Kabar pengunjung",
    qrSheetTitle: "Lembar QR booth",
    qrSheetHint: "Satu halaman A4 per booth. Cetak dari browser, kertas tanpa warna latar.",
    scanToStamp: "Scan untuk stempel paspor",
    print: "Cetak",
    stats: {
      tenants: "Tenant",
      tenantsContext: (booths: number, empty: number) => `dari ${booths} booth, ${empty} masih kosong`,
      questions: "Pertanyaan",
      questionsContext: (sessions: number, total: number, answered: number) => `di ${sessions} dari ${total} sesi, ${answered} sudah dijawab`,
      passportsStarted: "Paspor dimulai",
      passportsStartedContext: (avg: string) => `rata-rata ${avg} stempel per paspor`,
      passportsDone: "Paspor lengkap",
      passportsDoneContext: (n: number) => `${n} hadiah ditukar`,
    },
  },
  errors: {
    bodyTooShort: "Tulis minimal 3 karakter",
    bodyTooLong: "Maksimal 280 karakter",
    generic: "Terjadi kesalahan, coba lagi",
    invalidUrl: "Tautan tidak valid",
    fileTooLarge: "Ukuran file melebihi 5 MB",
    fileType: "Hanya file gambar yang bisa diunggah",
    photosFull: "Foto sudah 5, hapus satu dulu",
    timeFormat: "Tulis jam seperti 14.00",
  },
} as const;
